### ISSUE TITLE
out of sync video after render!

### ISSUE THREAD

**Issue by zacharyhub** [JargeZ/vhs#4]
I found out that video and audio were out of sync after rendering!

**Comment by JargeZ** [comment]
Hello, can you please tell me if there is a time with a black screen or an image without sound at the end of the video?
Was the render completely finished or was it partial?

And maybe you can send an example of a file with a video in which this was found in telegram: @JargeZ?

**Comment by zacharyhub** [comment]
render completely finished.

**Comment by Mr-Emerald** [comment]
continuing this thread, a more informative way of saying this would be the frame rate rounds down to the nearest whole number when exporting. for example 29.97 fps rounds down to 29 fps once exported and 59.94 fps rounds down to 59. the video also ends based on when the audio finishes rather than when the video finishes.
![explorer_RscN9Iw5ZV](https://user-images.githubusercontent.com/52552280/124449716-1118cb00-ddc7-11eb-9ffc-dff0c2b17b2a.png)
![explorer_v78AnnPklx](https://user-images.githubusercontent.com/52552280/124449732-14ac5200-ddc7-11eb-9262-557aebda6482.png)

**Comment by JargeZ** [comment]
Oh, @Mr-Emerald thank you very much for helpful a comment!

I will fix this by copying the exact frame rate when creating a video from the original video.
I forgot the existence of non-integer frames per second values, and used `int()`

**Comment by JargeZ** [comment]
Hi @Mr-Emerald and @zacharyhub 
Can you check this issue with build from this pre-release https://github.com/JargeZ/vhs/releases/tag/v1.5.0

**Comment by JargeZ** [comment]
By my checks, this should be fixed.
Reopen, if does not. Thank you!
